apiVersion: v1
kind: Endpoints
metadata:
  name: rabbitmq
  namespace: default
subsets:
  - addresses:
    - ip: 192.168.0.102
    ports:
      - port: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 5672